/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.AdministradorCtrl;
import model.Administrador;

/**
 *
 * @author PC GAMER
 */
public class FormCadAdm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormCadAdm.class.getName());

    /**
     * Creates new form FormCadAdm
     */
    public FormCadAdm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rtNome = new javax.swing.JLabel();
        rtSenha = new javax.swing.JLabel();
        rtDataNasc = new javax.swing.JLabel();
        rtCpf = new javax.swing.JLabel();
        rtTipoAtiv = new javax.swing.JLabel();
        cxNome = new javax.swing.JTextField();
        cxSenha = new javax.swing.JTextField();
        cxDataNasc = new javax.swing.JTextField();
        cxCpf = new javax.swing.JTextField();
        cxTipoAtiv = new javax.swing.JTextField();
        btCadAdm = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        rtNome.setText("Nome:");

        rtSenha.setText("Senha:");

        rtDataNasc.setText("Data de Nascimento:");

        rtCpf.setText("CPF:");

        rtTipoAtiv.setText("Tipo de Atividade:");

        btCadAdm.setText("Cadastrar");
        btCadAdm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadAdmActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(rtSenha)
                        .addComponent(rtNome))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(rtCpf)
                            .addComponent(rtDataNasc)
                            .addComponent(rtTipoAtiv))
                        .addGap(1, 1, 1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btCadAdm)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(cxNome)
                        .addComponent(cxSenha)
                        .addComponent(cxDataNasc)
                        .addComponent(cxCpf)
                        .addComponent(cxTipoAtiv, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rtNome)
                    .addComponent(cxNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rtSenha)
                    .addComponent(cxSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rtDataNasc)
                    .addComponent(cxDataNasc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rtCpf)
                    .addComponent(cxCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rtTipoAtiv)
                    .addComponent(cxTipoAtiv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(btCadAdm)
                .addContainerGap(53, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btCadAdmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadAdmActionPerformed
        Administrador administradores = new Administrador();
        administradores.setNome(cxNome.getText());
        administradores.setSenha(Integer.parseInt(cxSenha.getText()));
        administradores.setDataNasc(Integer.parseInt(cxDataNasc.getText()));
        administradores.setCpf(Integer.parseInt(cxCpf.getText()));
        administradores.setTipoAtividade(cxTipoAtiv.getText());
        AdministradorCtrl ctrl = new AdministradorCtrl();
        ctrl.adiciona(administradores);
    }//GEN-LAST:event_btCadAdmActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCadAdm;
    private javax.swing.JTextField cxCpf;
    private javax.swing.JTextField cxDataNasc;
    private javax.swing.JTextField cxNome;
    private javax.swing.JTextField cxSenha;
    private javax.swing.JTextField cxTipoAtiv;
    private javax.swing.JLabel rtCpf;
    private javax.swing.JLabel rtDataNasc;
    private javax.swing.JLabel rtNome;
    private javax.swing.JLabel rtSenha;
    private javax.swing.JLabel rtTipoAtiv;
    // End of variables declaration//GEN-END:variables
}
