package view;

import model.Cliente;
import model.ClienteDAO;
import controller.ReceitaCtrl;
import model.Receita;
import javax.swing.JOptionPane; 
import model.MedicamentoComumDAO;
import model.MedicamentoControladoDAO;
import model.MedicamentoComum;
import model.MedicamentoControlado;
import java.util.List;
public class FormCadReceita extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormCadReceita.class.getName());

 
    public FormCadReceita() {
        initComponents();
        carregarMedicamentos();
    }
    private void carregarMedicamentos() {
    try {
        cxNomeMedicamento.removeAllItems();
        cxNomeMedicamento.addItem("-- Selecione o Medicamento --"); 

        MedicamentoComumDAO comumDao = new MedicamentoComumDAO();
        List<MedicamentoComum> comuns = comumDao.listarTodos();
        for (MedicamentoComum med : comuns) {
            cxNomeMedicamento.addItem(med.getNome());
        }

        MedicamentoControladoDAO controladoDao = new MedicamentoControladoDAO();
        List<MedicamentoControlado> controlados = controladoDao.listarTodos();
        for (MedicamentoControlado med : controlados) {
            cxNomeMedicamento.addItem(med.getNome() + " (Controlado)");
        }
    } catch (Exception e) {
        logger.log(java.util.logging.Level.SEVERE, "Erro ao carregar lista de medicamentos", e);
        JOptionPane.showMessageDialog(this, "Erro ao carregar medicamentos.", "Erro de Banco", JOptionPane.ERROR_MESSAGE);
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btCadReceita = new javax.swing.JButton();
        rtCnpj = new javax.swing.JLabel();
        cxData = new javax.swing.JTextField();
        rtData = new javax.swing.JLabel();
        rtPosologia = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        cxPosologia = new javax.swing.JTextArea();
        rtNomedicamento = new javax.swing.JLabel();
        cxCPF1 = new javax.swing.JTextField();
        cxNomeMedicamento = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btCadReceita.setText("Cadastrar");
        btCadReceita.addActionListener(this::btCadReceitaActionPerformed);

        rtCnpj.setText("CPF:");

        cxData.addActionListener(this::cxDataActionPerformed);

        rtData.setText("Data:");

        rtPosologia.setText("Posologia:");

        cxPosologia.setColumns(20);
        cxPosologia.setRows(5);
        jScrollPane1.setViewportView(cxPosologia);

        rtNomedicamento.setText("Nome do Medicamento:");

        cxCPF1.addActionListener(this::cxCPF1ActionPerformed);

        cxNomeMedicamento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cxNomeMedicamento.addActionListener(this::cxNomeMedicamentoActionPerformed);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Cadastro de Receita");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btCadReceita)
                .addGap(196, 196, 196))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(rtData)
                            .addComponent(rtPosologia)
                            .addComponent(rtNomedicamento))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cxData, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cxNomeMedicamento, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(rtCnpj)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cxCPF1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(104, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rtCnpj)
                    .addComponent(cxCPF1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rtNomedicamento)
                    .addComponent(cxNomeMedicamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cxData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rtData))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rtPosologia))
                .addGap(18, 18, 18)
                .addComponent(btCadReceita)
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btCadReceitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadReceitaActionPerformed
   String cpfCliente = cxCPF1.getText().trim();
    String nomeMedCompleto = (String) cxNomeMedicamento.getSelectedItem(); 
    
    int idClienteReal = 0;
    
    ClienteDAO clienteDao = new ClienteDAO();
    Cliente clienteEncontrado = clienteDao.buscarPorCpf(cpfCliente); 

    if (clienteEncontrado == null) {
        javax.swing.JOptionPane.showMessageDialog(this, "Cliente não encontrado ou CPF inválido.", "Erro", javax.swing.JOptionPane.ERROR_MESSAGE);
        return; 
    }
    
    idClienteReal = 1; 

    
    if (nomeMedCompleto == null || nomeMedCompleto.startsWith("--")) {
        javax.swing.JOptionPane.showMessageDialog(this, "Selecione um medicamento válido.", "Erro", javax.swing.JOptionPane.ERROR_MESSAGE);
        return;
    }
    
    String nomeMed = nomeMedCompleto.replace(" (Controlado)", "").trim(); 

    
    Receita novaReceita = new Receita();
    novaReceita.setClienteId(idClienteReal);
    novaReceita.setNomeMedicamento(nomeMed);
    novaReceita.setDataEmissao(cxData.getText()); 
    novaReceita.setPosologia(cxPosologia.getText()); 

    ReceitaCtrl ctrl = new ReceitaCtrl();
    ctrl.adiciona(novaReceita);
    }//GEN-LAST:event_btCadReceitaActionPerformed
 
    private void cxCPF1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxCPF1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cxCPF1ActionPerformed

    private void cxDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxDataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cxDataActionPerformed

    private void cxNomeMedicamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxNomeMedicamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cxNomeMedicamentoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormCadReceita().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCadReceita;
    private javax.swing.JTextField cxCPF1;
    private javax.swing.JTextField cxData;
    private javax.swing.JComboBox<String> cxNomeMedicamento;
    private javax.swing.JTextArea cxPosologia;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel rtCnpj;
    private javax.swing.JLabel rtData;
    private javax.swing.JLabel rtNomedicamento;
    private javax.swing.JLabel rtPosologia;
    // End of variables declaration//GEN-END:variables
}
