/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.MedicamentoComumCtrl;
import model.MedicamentoComum;

/**
 *
 * @author PC GAMER
 */
public class FormCadMedComum extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormCadMedComum.class.getName());

    /**
     * Creates new form FormCadMedComum
     */
    public FormCadMedComum() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rtNome = new javax.swing.JLabel();
        rtTipoControle = new javax.swing.JLabel();
        rtDosagem = new javax.swing.JLabel();
        rtIndicacao = new javax.swing.JLabel();
        cxNome = new javax.swing.JTextField();
        cxTipoControle = new javax.swing.JTextField();
        cxDosagem = new javax.swing.JTextField();
        cxIndicacao = new javax.swing.JTextField();
        btCadMedComum = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        rtNome.setText("Nome:");

        rtTipoControle.setText("Tipo de Controle:");

        rtDosagem.setText("Dosagem:");

        rtIndicacao.setText("Indicação:");

        cxDosagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxDosagemActionPerformed(evt);
            }
        });

        btCadMedComum.setText("Cadastrar");
        btCadMedComum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadMedComumActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Cadastro de Medicamento Comum");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(rtIndicacao)
                    .addComponent(rtDosagem)
                    .addComponent(rtTipoControle)
                    .addComponent(rtNome))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cxIndicacao, javax.swing.GroupLayout.DEFAULT_SIZE, 297, Short.MAX_VALUE)
                    .addComponent(cxNome)
                    .addComponent(cxTipoControle)
                    .addComponent(cxDosagem))
                .addGap(57, 57, 57))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(47, 47, 47))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btCadMedComum)
                        .addGap(188, 188, 188))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rtNome)
                    .addComponent(cxNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rtTipoControle)
                    .addComponent(cxTipoControle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rtDosagem)
                    .addComponent(cxDosagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rtIndicacao)
                    .addComponent(cxIndicacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(btCadMedComum)
                .addGap(34, 34, 34))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cxDosagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxDosagemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cxDosagemActionPerformed

    private void btCadMedComumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadMedComumActionPerformed
        MedicamentoComum medicamentosComuns = new MedicamentoComum();
        medicamentosComuns.setNome(cxNome.getText());
        medicamentosComuns.setTipoControle(cxTipoControle.getText());
        medicamentosComuns.setDosagem(cxDosagem.getText());
        medicamentosComuns.setIndicacao(cxIndicacao.getText());
        MedicamentoComumCtrl ctrl = new MedicamentoComumCtrl();
        ctrl.adiciona(medicamentosComuns);
    }//GEN-LAST:event_btCadMedComumActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCadMedComum;
    private javax.swing.JTextField cxDosagem;
    private javax.swing.JTextField cxIndicacao;
    private javax.swing.JTextField cxNome;
    private javax.swing.JTextField cxTipoControle;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel rtDosagem;
    private javax.swing.JLabel rtIndicacao;
    private javax.swing.JLabel rtNome;
    private javax.swing.JLabel rtTipoControle;
    // End of variables declaration//GEN-END:variables
}
