/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.MedicamentoControladoCtrl;
import model.MedicamentoControlado;

/**
 *
 * @author PC GAMER
 */
public class FormCadMedControlado extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormCadMedControlado.class.getName());

    /**
     * Creates new form FormCadMedControlado
     */
    public FormCadMedControlado() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rtNome = new javax.swing.JLabel();
        rtTipoControle = new javax.swing.JLabel();
        rtDosagem = new javax.swing.JLabel();
        rtNumReceita = new javax.swing.JLabel();
        rtValReceita = new javax.swing.JLabel();
        rtDescricao = new javax.swing.JLabel();
        cxNome = new javax.swing.JTextField();
        cxTipoControle = new javax.swing.JTextField();
        cxDosagem = new javax.swing.JTextField();
        cxNumReceita = new javax.swing.JTextField();
        cxValReceita = new javax.swing.JTextField();
        cxDescricao = new javax.swing.JTextField();
        btCadMedControlado = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        rtNome.setText("Nome:");

        rtTipoControle.setText("Tipo de Controle:");

        rtDosagem.setText("Dosagem:");

        rtNumReceita.setText("Número da Receita:");

        rtValReceita.setText("Validade da Receita:");

        rtDescricao.setText("Descrição:");

        btCadMedControlado.setText("Cadastrar");
        btCadMedControlado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadMedControladoActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Cadastro de Medicamento Controlado");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(rtDescricao)
                                    .addComponent(rtValReceita)
                                    .addComponent(rtNumReceita)
                                    .addComponent(rtDosagem)
                                    .addComponent(rtTipoControle)
                                    .addComponent(rtNome))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cxNome)
                                    .addComponent(cxTipoControle)
                                    .addComponent(cxDosagem)
                                    .addComponent(cxNumReceita)
                                    .addComponent(cxValReceita)
                                    .addComponent(cxDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btCadMedControlado)
                                .addGap(94, 94, 94)))))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rtNome)
                    .addComponent(cxNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rtTipoControle)
                    .addComponent(cxTipoControle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rtDosagem)
                    .addComponent(cxDosagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rtNumReceita)
                    .addComponent(cxNumReceita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rtValReceita)
                    .addComponent(cxValReceita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rtDescricao)
                    .addComponent(cxDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(btCadMedControlado)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btCadMedControladoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadMedControladoActionPerformed
        MedicamentoControlado medicamentosControlados = new MedicamentoControlado();
        medicamentosControlados.setNome(cxNome.getText());
        medicamentosControlados.setTipoControle(cxTipoControle.getText());
        medicamentosControlados.setDosagem(cxDosagem.getText());
        medicamentosControlados.setNumReceita(cxNumReceita.getText());
        medicamentosControlados.setValReceita(cxValReceita.getText());
        medicamentosControlados.setDescricao(cxDescricao.getText());
        MedicamentoControladoCtrl ctrl = new MedicamentoControladoCtrl();
        ctrl.adiciona(medicamentosControlados);
    }//GEN-LAST:event_btCadMedControladoActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCadMedControlado;
    private javax.swing.JTextField cxDescricao;
    private javax.swing.JTextField cxDosagem;
    private javax.swing.JTextField cxNome;
    private javax.swing.JTextField cxNumReceita;
    private javax.swing.JTextField cxTipoControle;
    private javax.swing.JTextField cxValReceita;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel rtDescricao;
    private javax.swing.JLabel rtDosagem;
    private javax.swing.JLabel rtNome;
    private javax.swing.JLabel rtNumReceita;
    private javax.swing.JLabel rtTipoControle;
    private javax.swing.JLabel rtValReceita;
    // End of variables declaration//GEN-END:variables
}
