/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.Relatorio;
import controller.LoginCtrl;

/**
 *
 * @author PC GAMER
 */
public class TelaPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaPrincipal.class.getName());
    private LoginCtrl.TipoUsuario nivelAcesso;
    
    public TelaPrincipal(LoginCtrl.TipoUsuario nivelAcesso) {
        this.nivelAcesso = nivelAcesso; 
        initComponents();
        configurarAcesso(nivelAcesso); 
    }

    public TelaPrincipal() {
        initComponents();
    }
    
    private void configurarAcesso(LoginCtrl.TipoUsuario nivel) {
        if (nivel == LoginCtrl.TipoUsuario.FUNCIONARIO) {
            
            mnRel.setVisible(false);
            
            itMnCadAdm.setVisible(false);
            
            rtTelaPrinc.setText("Bem vindo Funcionário!");
        } else if (nivel == LoginCtrl.TipoUsuario.ADMINISTRADOR) {
            rtTelaPrinc.setText("Bem vindo Administrador!");
        }
    }
/**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaPrincipal().setVisible(true));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rtTelaPrinc = new javax.swing.JLabel();
        rtTelaPrinc1 = new javax.swing.JLabel();
        btCRM = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnCad = new javax.swing.JMenu();
        itMnCadFunc = new javax.swing.JMenuItem();
        itMnCadFarm = new javax.swing.JMenuItem();
        itMnCadAdm = new javax.swing.JMenuItem();
        itMnCadCliente = new javax.swing.JMenuItem();
        jMnCadReceita = new javax.swing.JMenuItem();
        itMnCadFornec = new javax.swing.JMenuItem();
        mnCadMed = new javax.swing.JMenu();
        itMnCadMedComum = new javax.swing.JMenuItem();
        itMnCadMedControlado = new javax.swing.JMenuItem();
        itMnCadProd = new javax.swing.JMenuItem();
        mnRel = new javax.swing.JMenu();
        itMnRelFunc = new javax.swing.JMenuItem();
        itMnRelFarm = new javax.swing.JMenuItem();
        itMnRelAdm = new javax.swing.JMenuItem();
        itMnRelCliente = new javax.swing.JMenuItem();
        itMnRelFornec = new javax.swing.JMenuItem();
        mnRelMed = new javax.swing.JMenu();
        itMnRelMedComum = new javax.swing.JMenuItem();
        itMnRelMedControlado = new javax.swing.JMenuItem();
        itMnRelProd = new javax.swing.JMenuItem();
        mnRec = new javax.swing.JMenu();
        mnSaida = new javax.swing.JMenu();
        itMnSaidaProduto = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        rtTelaPrinc.setBackground(new java.awt.Color(0, 0, 0));
        rtTelaPrinc.setFont(new java.awt.Font("High Tower Text", 1, 24)); // NOI18N
        rtTelaPrinc.setText("Bem vindo Administrador!");

        rtTelaPrinc1.setBackground(new java.awt.Color(0, 0, 0));
        rtTelaPrinc1.setFont(new java.awt.Font("High Tower Text", 1, 24)); // NOI18N
        rtTelaPrinc1.setText("SaudeHub");

        btCRM.setText("Consultar CRM");
        btCRM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCRMActionPerformed(evt);
            }
        });

        mnCad.setText("Cadastros");

        itMnCadFunc.setText("Cadastrar Funcionário");
        itMnCadFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itMnCadFuncActionPerformed(evt);
            }
        });
        mnCad.add(itMnCadFunc);

        itMnCadFarm.setText("Cadastrar Farmacêutico");
        itMnCadFarm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itMnCadFarmActionPerformed(evt);
            }
        });
        mnCad.add(itMnCadFarm);

        itMnCadAdm.setText("Cadastrar Administrador");
        itMnCadAdm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itMnCadAdmActionPerformed(evt);
            }
        });
        mnCad.add(itMnCadAdm);

        itMnCadCliente.setText("Cadastrar Cliente");
        itMnCadCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itMnCadClienteActionPerformed(evt);
            }
        });
        mnCad.add(itMnCadCliente);

        jMnCadReceita.setText("Cadastrar Receita ");
        jMnCadReceita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnCadReceitaActionPerformed(evt);
            }
        });
        mnCad.add(jMnCadReceita);

        itMnCadFornec.setText("Cadastrar Fornecedor");
        itMnCadFornec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itMnCadFornecActionPerformed(evt);
            }
        });
        mnCad.add(itMnCadFornec);

        mnCadMed.setText("Cadastrar Medicamentos");

        itMnCadMedComum.setText("Medicamentos Comuns");
        itMnCadMedComum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itMnCadMedComumActionPerformed(evt);
            }
        });
        mnCadMed.add(itMnCadMedComum);

        itMnCadMedControlado.setText("Medicamentos Controlados");
        itMnCadMedControlado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itMnCadMedControladoActionPerformed(evt);
            }
        });
        mnCadMed.add(itMnCadMedControlado);

        mnCad.add(mnCadMed);

        itMnCadProd.setText("Cadastrar Produto");
        itMnCadProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itMnCadProdActionPerformed(evt);
            }
        });
        mnCad.add(itMnCadProd);

        jMenuBar1.add(mnCad);

        mnRel.setText("Relatórios");

        itMnRelFunc.setText("Funcionários");
        itMnRelFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itMnRelFuncActionPerformed(evt);
            }
        });
        mnRel.add(itMnRelFunc);

        itMnRelFarm.setText("Farmacêuticos");
        itMnRelFarm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itMnRelFarmActionPerformed(evt);
            }
        });
        mnRel.add(itMnRelFarm);

        itMnRelAdm.setText("Administradores");
        itMnRelAdm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itMnRelAdmActionPerformed(evt);
            }
        });
        mnRel.add(itMnRelAdm);

        itMnRelCliente.setText("Clientes");
        itMnRelCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itMnRelClienteActionPerformed(evt);
            }
        });
        mnRel.add(itMnRelCliente);

        itMnRelFornec.setText("Fornecedores");
        itMnRelFornec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itMnRelFornecActionPerformed(evt);
            }
        });
        mnRel.add(itMnRelFornec);

        mnRelMed.setText("Medicamentos");

        itMnRelMedComum.setText("Medicamentos Comuns");
        itMnRelMedComum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itMnRelMedComumActionPerformed(evt);
            }
        });
        mnRelMed.add(itMnRelMedComum);

        itMnRelMedControlado.setText("Medicamentos Controlados");
        itMnRelMedControlado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itMnRelMedControladoActionPerformed(evt);
            }
        });
        mnRelMed.add(itMnRelMedControlado);

        mnRel.add(mnRelMed);

        itMnRelProd.setText("Produtos");
        itMnRelProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itMnRelProdActionPerformed(evt);
            }
        });
        mnRel.add(itMnRelProd);

        jMenuBar1.add(mnRel);

        mnRec.setText("Receitas");
        mnRec.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnRecMouseClicked(evt);
            }
        });
        mnRec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnRecActionPerformed(evt);
            }
        });
        jMenuBar1.add(mnRec);

        mnSaida.setText("Saída");

        itMnSaidaProduto.setText("Produtos");
        itMnSaidaProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itMnSaidaProdutoActionPerformed(evt);
            }
        });
        mnSaida.add(itMnSaidaProduto);

        jMenuBar1.add(mnSaida);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(rtTelaPrinc)
                .addContainerGap(99, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(rtTelaPrinc1)
                        .addGap(182, 182, 182))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btCRM, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(rtTelaPrinc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rtTelaPrinc1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 112, Short.MAX_VALUE)
                .addComponent(btCRM)
                .addGap(35, 35, 35))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itMnRelFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itMnRelFuncActionPerformed
        Relatorio relatorio = new Relatorio();
        relatorio.gerarRelatorioFuncionarios();
    }//GEN-LAST:event_itMnRelFuncActionPerformed

    private void itMnRelFarmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itMnRelFarmActionPerformed
        Relatorio relatorio = new Relatorio();
        relatorio.gerarRelatorioFarmaceuticos();
    }//GEN-LAST:event_itMnRelFarmActionPerformed

    private void itMnRelAdmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itMnRelAdmActionPerformed
        Relatorio relatorio = new Relatorio();
        relatorio.gerarRelatorioAdministradores();
    }//GEN-LAST:event_itMnRelAdmActionPerformed

    private void itMnRelClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itMnRelClienteActionPerformed
        Relatorio relatorio = new Relatorio();
        relatorio.gerarRelatorioClientes();
    }//GEN-LAST:event_itMnRelClienteActionPerformed

    private void itMnRelFornecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itMnRelFornecActionPerformed
        Relatorio relatorio = new Relatorio();
        relatorio.gerarRelatorioFornecedores();
    }//GEN-LAST:event_itMnRelFornecActionPerformed

    private void itMnRelMedComumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itMnRelMedComumActionPerformed
        Relatorio relatorio = new Relatorio();
        relatorio.gerarRelatorioMedComum();
    }//GEN-LAST:event_itMnRelMedComumActionPerformed

    private void itMnRelMedControladoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itMnRelMedControladoActionPerformed
        Relatorio relatorio = new Relatorio();
        relatorio.gerarRelatorioMedControlado();
    }//GEN-LAST:event_itMnRelMedControladoActionPerformed

    private void itMnRelProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itMnRelProdActionPerformed
        Relatorio relatorio = new Relatorio();
        relatorio.gerarRelatorioProdutos();
    }//GEN-LAST:event_itMnRelProdActionPerformed

    private void itMnCadProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itMnCadProdActionPerformed
        FormCadProduto form = new FormCadProduto();
        form.setVisible(true);
    }//GEN-LAST:event_itMnCadProdActionPerformed

    private void itMnCadMedControladoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itMnCadMedControladoActionPerformed
        FormCadMedControlado form = new FormCadMedControlado();
        form.setVisible(true);
    }//GEN-LAST:event_itMnCadMedControladoActionPerformed

    private void itMnCadMedComumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itMnCadMedComumActionPerformed
        FormCadMedComum form = new FormCadMedComum();
        form.setVisible(true);
    }//GEN-LAST:event_itMnCadMedComumActionPerformed

    private void itMnCadFornecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itMnCadFornecActionPerformed
        FormCadFornec form = new FormCadFornec();
        form.setVisible(true);
    }//GEN-LAST:event_itMnCadFornecActionPerformed

    private void itMnCadClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itMnCadClienteActionPerformed
        FormCadCliente form = new FormCadCliente();
        form.setVisible(true);
    }//GEN-LAST:event_itMnCadClienteActionPerformed

    private void itMnCadAdmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itMnCadAdmActionPerformed
        FormCadAdm form = new FormCadAdm();
        form.setVisible(true);
    }//GEN-LAST:event_itMnCadAdmActionPerformed

    private void itMnCadFarmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itMnCadFarmActionPerformed
        FormCadFarm form = new FormCadFarm();
        form.setVisible(true);
    }//GEN-LAST:event_itMnCadFarmActionPerformed

    private void itMnCadFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itMnCadFuncActionPerformed
        FormCadFunc form = new FormCadFunc();
        form.setVisible(true);
    }//GEN-LAST:event_itMnCadFuncActionPerformed

    private void btCRMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCRMActionPerformed
        try {
    
    String urlDoCRM = "https://portal.cfm.org.br/busca-medicos/"; 
    
   
    if (java.awt.Desktop.isDesktopSupported()) {
        java.awt.Desktop desktop = java.awt.Desktop.getDesktop();
        
        
        if (desktop.isSupported(java.awt.Desktop.Action.BROWSE)) {
            
            
            java.net.URI uri = new java.net.URI(urlDoCRM);
            desktop.browse(uri);
        } else {
            
            javax.swing.JOptionPane.showMessageDialog(this, 
                "Seu sistema não suporta a abertura automática de links.", 
                "Erro de Navegação", 
                javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    } else {
        
        javax.swing.JOptionPane.showMessageDialog(this, 
            "A classe Desktop não é suportada neste ambiente.", 
            "Erro de Ambiente", 
            javax.swing.JOptionPane.ERROR_MESSAGE);
    }
} catch (java.io.IOException | java.net.URISyntaxException ex) {
    
    javax.swing.JOptionPane.showMessageDialog(this, 
        "Ocorreu um erro ao tentar abrir o link: " + ex.getMessage(), 
        "Erro", 
        javax.swing.JOptionPane.ERROR_MESSAGE);
}
    }//GEN-LAST:event_btCRMActionPerformed

    private void jMnCadReceitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnCadReceitaActionPerformed
        FormCadReceita form = new FormCadReceita();
        form.setVisible(true);
    }//GEN-LAST:event_jMnCadReceitaActionPerformed

    private void mnRecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnRecActionPerformed
        
    }//GEN-LAST:event_mnRecActionPerformed

    private void mnRecMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnRecMouseClicked
        Relatorio relatorio = new Relatorio();
        relatorio.gerarRelatorioReceitas();
    }//GEN-LAST:event_mnRecMouseClicked

    private void itMnSaidaProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itMnSaidaProdutoActionPerformed
        FormSaidaProduto form = new FormSaidaProduto();
        form.setVisible(true);
    }//GEN-LAST:event_itMnSaidaProdutoActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCRM;
    private javax.swing.JMenuItem itMnCadAdm;
    private javax.swing.JMenuItem itMnCadCliente;
    private javax.swing.JMenuItem itMnCadFarm;
    private javax.swing.JMenuItem itMnCadFornec;
    private javax.swing.JMenuItem itMnCadFunc;
    private javax.swing.JMenuItem itMnCadMedComum;
    private javax.swing.JMenuItem itMnCadMedControlado;
    private javax.swing.JMenuItem itMnCadProd;
    private javax.swing.JMenuItem itMnRelAdm;
    private javax.swing.JMenuItem itMnRelCliente;
    private javax.swing.JMenuItem itMnRelFarm;
    private javax.swing.JMenuItem itMnRelFornec;
    private javax.swing.JMenuItem itMnRelFunc;
    private javax.swing.JMenuItem itMnRelMedComum;
    private javax.swing.JMenuItem itMnRelMedControlado;
    private javax.swing.JMenuItem itMnRelProd;
    private javax.swing.JMenuItem itMnSaidaProduto;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMnCadReceita;
    private javax.swing.JMenu mnCad;
    private javax.swing.JMenu mnCadMed;
    private javax.swing.JMenu mnRec;
    private javax.swing.JMenu mnRel;
    private javax.swing.JMenu mnRelMed;
    private javax.swing.JMenu mnSaida;
    private javax.swing.JLabel rtTelaPrinc;
    private javax.swing.JLabel rtTelaPrinc1;
    // End of variables declaration//GEN-END:variables
}
