/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author PC GAMER
 */
public class TelaPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaPrincipal.class.getName());

    /**
     * Creates new form FormCadFunc
     */
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rtTelaPrinc = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnCad = new javax.swing.JMenu();
        itMnCadFunc = new javax.swing.JMenuItem();
        itMnCadFarm = new javax.swing.JMenuItem();
        itMnCadAdm = new javax.swing.JMenuItem();
        itMnCadCliente = new javax.swing.JMenuItem();
        itMnCadFornec = new javax.swing.JMenuItem();
        mnCadMed = new javax.swing.JMenu();
        itMnCadMedComum = new javax.swing.JMenuItem();
        itMnCadMedControlado = new javax.swing.JMenuItem();
        itMnCadProd = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        rtTelaPrinc.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        rtTelaPrinc.setText("Tela Principal");

        mnCad.setText("Cadastros");

        itMnCadFunc.setText("Cadastrar Funcionário");
        itMnCadFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itMnCadFuncActionPerformed(evt);
            }
        });
        mnCad.add(itMnCadFunc);

        itMnCadFarm.setText("Cadastrar Farmacêutico");
        itMnCadFarm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itMnCadFarmActionPerformed(evt);
            }
        });
        mnCad.add(itMnCadFarm);

        itMnCadAdm.setText("Cadastrar Administrador");
        itMnCadAdm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itMnCadAdmActionPerformed(evt);
            }
        });
        mnCad.add(itMnCadAdm);

        itMnCadCliente.setText("Cadastrar Cliente");
        itMnCadCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itMnCadClienteActionPerformed(evt);
            }
        });
        mnCad.add(itMnCadCliente);

        itMnCadFornec.setText("Cadastrar Fornecedor");
        itMnCadFornec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itMnCadFornecActionPerformed(evt);
            }
        });
        mnCad.add(itMnCadFornec);

        mnCadMed.setText("Cadastrar Medicamentos");

        itMnCadMedComum.setText("Medicamentos Comuns");
        itMnCadMedComum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itMnCadMedComumActionPerformed(evt);
            }
        });
        mnCadMed.add(itMnCadMedComum);

        itMnCadMedControlado.setText("Medicamentos Controlados");
        itMnCadMedControlado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itMnCadMedControladoActionPerformed(evt);
            }
        });
        mnCadMed.add(itMnCadMedControlado);

        mnCad.add(mnCadMed);

        itMnCadProd.setText("Cadastrar Produto");
        itMnCadProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itMnCadProdActionPerformed(evt);
            }
        });
        mnCad.add(itMnCadProd);

        jMenuBar1.add(mnCad);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(121, 121, 121)
                .addComponent(rtTelaPrinc)
                .addContainerGap(140, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(rtTelaPrinc)
                .addContainerGap(224, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itMnCadFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itMnCadFuncActionPerformed
        FormCadFunc form = new FormCadFunc();
        form.setVisible(true); 
    }//GEN-LAST:event_itMnCadFuncActionPerformed

    private void itMnCadFarmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itMnCadFarmActionPerformed
        FormCadFarm form = new FormCadFarm();
        form.setVisible(true); 
    }//GEN-LAST:event_itMnCadFarmActionPerformed

    private void itMnCadAdmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itMnCadAdmActionPerformed
        FormCadAdm form = new FormCadAdm();
        form.setVisible(true); 
    }//GEN-LAST:event_itMnCadAdmActionPerformed

    private void itMnCadClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itMnCadClienteActionPerformed
        FormCadCliente form = new FormCadCliente();
        form.setVisible(true); 
    }//GEN-LAST:event_itMnCadClienteActionPerformed

    private void itMnCadFornecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itMnCadFornecActionPerformed
        FormCadFornec form = new FormCadFornec();
        form.setVisible(true); 
    }//GEN-LAST:event_itMnCadFornecActionPerformed

    private void itMnCadMedComumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itMnCadMedComumActionPerformed
        FormCadMedComum form = new FormCadMedComum();
        form.setVisible(true); 
    }//GEN-LAST:event_itMnCadMedComumActionPerformed

    private void itMnCadMedControladoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itMnCadMedControladoActionPerformed
        FormCadMedControlado form = new FormCadMedControlado();
        form.setVisible(true); 
    }//GEN-LAST:event_itMnCadMedControladoActionPerformed

    private void itMnCadProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itMnCadProdActionPerformed
        FormCadProduto form = new FormCadProduto();
        form.setVisible(true); 
    }//GEN-LAST:event_itMnCadProdActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem itMnCadAdm;
    private javax.swing.JMenuItem itMnCadCliente;
    private javax.swing.JMenuItem itMnCadFarm;
    private javax.swing.JMenuItem itMnCadFornec;
    private javax.swing.JMenuItem itMnCadFunc;
    private javax.swing.JMenuItem itMnCadMedComum;
    private javax.swing.JMenuItem itMnCadMedControlado;
    private javax.swing.JMenuItem itMnCadProd;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu mnCad;
    private javax.swing.JMenu mnCadMed;
    private javax.swing.JLabel rtTelaPrinc;
    // End of variables declaration//GEN-END:variables
}
